### ISSUE TITLE
Ignition v2 support is broken in Flatcar 3227.2.0 or newer

### ISSUE THREAD

**Issue by igcherkaev** [flatcar/Flatcar#828] opened 2022-08-18 22:36 UTC
## Description

Attempting to re-use ignition v2 configs with Flatcar image 3227.2.0 leads to a non-provisioned VM, which just offers an emergency shell or auto reboot in 5 min.

## Impact

Unable to provision new VMs in VMWare using ignition v2 configs.

## Environment and steps to reproduce

1. **Set-up**: 
  a. Download https://stable.release.flatcar-linux.net/amd64-usr/current/flatcar_production_vmware_ova.ova and deploy with ignition v2 configuration file.
2. **Task**: 
  a. Flatcar attempts to boot, runs ignition stage, doesn't print anything that'd point to any errors in the ignition config, thinks a bit and offers an emergency shell. Pressing Enter to enter it doesn't work, it just tries to re-run its boot sequence.
3. **Action(s)**: 
  a. Deploy OVA file downloaded from the official website.
  b. Put ignition config and its encoding into the guestinfo fields.
  c. Power on the VM.
4. **Error**: 
  a. Watch Flatcar not booting up.

## Expected behavior

VM provisioned, flatcar linux booted up to login prompt.

## Additional information

Taking image 3139.2.2 and re-doing same steps works perfectly fine. Updating to 3227.2.0 or newer using update_engine_client after successful provisioning doesn't cause any issues either.

The ignition config is fairly large and we put it in gzip+b64 format in guestinfo. Doing the same with image 3139.2.2 works just fine, we can see how ignition stage works, how it creates users and everything else (I can provide boot screenshots for 3139.2.2 too).

The following screenshots briefly show how ignition stage finished and what it ended up with. 

![Screenshot 2022-08-18 173139](https://user-images.githubusercontent.com/18666442/185506703-b4665190-7af6-4888-a674-6ba038620f1f.png)
![Screenshot 2022-08-18 173210](https://user-images.githubusercontent.com/18666442/185506705-4621ab0d-d2fe-4cdd-b6c8-3f5e8a361e2b.png)

**Comment by tormath1** [comment] 2022-08-19 06:42
Hi @igcherkaev,

VMWare is tested with `guestinfo.ignition.config.data.encoding` set to `base64`. I would assume yours is `gzip+base64`? Could you try to boot the instance with `systemd.log_level=debug systemd.log_target=kmsg log_buf_len=1M printk.devkmsg=on` to try getting more logs?

If you have access to the emergency shell could you identified the failing stage (`systemctl --failed`) and provide the logs for the failing unit?

**Comment by jepio** [comment] 2022-08-19 07:36
Please attach your ignition config so that we can test it ourselves (censor out any secrets that may be contained within).

**Comment by pothos** [comment] 2022-08-19 09:38
Would be great to add this to the release test suite

**Comment by igcherkaev** [comment] 2022-08-24 15:07
Sorry, guys, I am a bit swamped right now, but I'll get you all the requested information as soon as possible!

**Comment by igcherkaev** [comment] 2022-08-24 15:09
> VMWare is tested with `guestinfo.ignition.config.data.encoding` set to `base64`. I would assume yours is `gzip+base64`? Could you try to boot the instance with `systemd.log_level=debug systemd.log_target=kmsg log_buf_len=1M printk.devkmsg=on` to try getting more logs?
> 
> If you have access to the emergency shell could you identified the failing stage (`systemctl --failed`) and provide the logs for the failing unit?

Hi @tormath1 ! I'll try that to see if it reveals the underlying issue, but as I said, it doesn't really let me into the emergency shell. It just keeps attempting to boot over and over (without actual reboot of the whole VM) if I press Enter when prompted.

**Comment by igcherkaev** [comment] 2022-09-19 18:12
Hi folks.

Finally found some time to try the options/troubleshooting steps suggested above, but it doesn't look like it revealed anything new to me. 

Could someone try to reproduce the issue with the following ignition config (gzipped and encoded with base64): https://gist.github.com/igcherkaev/7b1cf58ada8fadbff3e84461c9918ea4 ?

VMWare guest Info was set as following:

![image](https://user-images.githubusercontent.com/18666442/191085269-cc1ea661-bfa5-4f49-b902-bcad1571fadc.png)
![image](https://user-images.githubusercontent.com/18666442/191085334-360c3acf-c900-47e1-981f-8006445c4991.png)

**Comment by igcherkaev** [comment] 2022-09-19 18:42
It boots just fine with the same guestInfo data with the 3139.2.2 ova image:
![image](https://user-images.githubusercontent.com/18666442/191091687-e19248a6-e83c-4746-a0da-b2fc5f51fa2b.png)

**Comment by jepio** [comment] 2022-09-20 06:59
@igcherkaev 

you have multiple conflicting entries in the `systemd` section for the key `etcd-member.service`. These are not accepted any longer, we are looking to restore that but for now you'll need to manually merge the entries into one.

**Comment by pothos** [comment] 2022-09-20 10:40
The fix is being prepared in https://github.com/flatcar-linux/ign-converter/pull/9

**Comment by igcherkaev** [comment] 2022-09-20 16:04
> you have multiple conflicting entries in the `systemd` section for the key `etcd-member.service`. These are not accepted any longer, we are looking to restore that but for now you'll need to manually merge the entries into one.

I see. Thanks for pointing it out! It's just we didn't expect things to break since we kept using old ignition version (v2). I'll work on my ignition config generator/templates to make sure we don't create conflicting entries for services.

**Comment by pothos** [comment] 2022-09-20 16:14
If you can continue to deploy the old Flatcar version and let it directly update, that would be a temporary solution until we fix this. We didn't expect this to break so subtle, v2 should work without problem hopefully after fixing this.

**Comment by igcherkaev** [comment] 2022-09-20 16:57
OK. However, I merged that conflicting entry for etcd-member.service by hand and tried again. Even ran it with `ct-config -strict`, it generated a configuration without any warnings. Unfortunately, ran into same issue. 3227.2.0 doesn't boot with it.
```
$ ct-config -version
ct v0.9.0
```

**Comment by jepio** [comment] 2022-09-20 17:30
`/etc/coreos/update.conf` is also a duplicate (and will collide with `/etc/flatcar/update.conf`) so you need to fix those as well.

The way I verify this is:
```
git clone https://github.com/flatcar/ign-converter
cd ign-converter
go build -o ign-converter internal/main.go
./ign-converter < config.ign
```

This is the same code that runs during boot to convert ignition from v2 to v3.

@pothos / @tormath1 I had this idea once of having `./ct` have a mode where it runs the conversion directly and shows any errors that might occur.

**Comment by igcherkaev** [comment] 2022-09-20 18:30
@jepio , thanks! It turns out, ct-config creates those duplicates for me... In a sense, that when I need to add a drop-in for etcd-member.service, it creates a separate unit in addition to its own pre-generated etcd-member.service unit... In that case the fix by @pothos should help, I guess.

**Comment by igcherkaev** [comment] 2022-09-20 18:49
After running it through ign-converter and having no errors printed, it indeed tried to boot with it, but failed with:

![Screenshot 2022-09-20 134652](https://user-images.githubusercontent.com/18666442/191339802-ef341ab6-315f-4268-916d-faf6efe482dd.png)

Emergency shell isn't usable as it keeps trying to boot over and over, not letting you type anything. Not sure how to stop this boot loop in order to troubleshoot it or collect logs.

**Comment by jepio** [comment] 2022-09-22 09:16
This is weird. Can you try debugging it (collecting logs) in QEMU, you can follow these docs https://flatcar-linux.org/docs/latest/installing/vms/qemu/ and then pass the ign like so: `./flatcar_production_qemu.sh -i config.ign -curses`.

I tried fixing up your original ignition file and came up with the following that boots in qemu: [config.json.txt](https://github.com/flatcar/Flatcar/files/9624260/config.json.txt)

**Comment by igcherkaev** [comment] 2022-09-22 17:38
@jepio I could try, but what if the issue is vmware specific? Anyway, I'll try to reproduce it with qemu and report back.

**Comment by jepio** [comment] 2022-09-23 06:47
If the issue is vmware specific then we'll need to look at reproducing on vmware, but this is not typically the case for ignition boot problems. The ignition config should either work on all platforms or on none.

**Comment by igcherkaev** [comment] 2022-09-27 20:55
OK, the problem was that the flatcar image has `/etc/flatcar/update.conf` symlink to `/etc/coreos/update.conf` and my ignition config had file content (re)defined for `/etc/flatcar/update.conf`, which ignition couldn't write to disk because of the existing symlink.

**Comment by igcherkaev** [comment] 2022-09-28 02:29
P.S. Had the emergency shell worked in vmware image, it would've been much easier to troubleshoot and most likely this issue wouldn't have been raised :)

**Comment by pothos** [comment] 2023-03-17 06:58
Writing `/etc/flatcar/update.conf` through Ignition should work. The `/etc/coreos` symlink to `/etc/flatcar` is there for compatibility but as long as you use a new image `/etc/coreos` won't be a directory, even if you specify `/etc/coreos/update.conf` in your ignition config.

Tested with
```
{
  "ignition": {
    "config": {},
    "security": {
      "tls": {}
    },
    "timeouts": {},
    "version": "2.3.0"
  },
  "networkd": {},
  "passwd": {},
  "storage": {
    "files": [
      {
        "filesystem": "root",
        "path": "/etc/coreos/update.conf",
        "contents": {
          "source": "data:,SERVER%3Dhttp%3A%2F%2F192.168.0.30%3A8000%2Fv1%2Fupdate%0A",
          "verification": {}
        },
        "mode": 420
      }
    ]
  },
  "systemd": {}
}
```

**Comment by pothos** [comment] 2023-05-22 16:11
We can close this now, or? The initial bug was addressed. Please report any problems again as new issue.

**Closed as completed by pothos** 2023-05-22 16:11 UTC
Labels: kind/bug, component/ignition
