### ISSUE TITLE
Containers with no-new-privileges don't start on Flatcar alpha 2492.0.0

### ISSUE THREAD

**Issue by iaguis** [flatcar/Flatcar#110] opened 2020-05-05 09:47 UTC
**Description**

I'm seeing errors running pods in nodes with latest Flatcar alpha (2492.0.0):

```
standard_init_linux.go:211: exec user process caused "operation not permitted"
```

it seems to be pods with `allowPrivilegeEscalation: false`.

Things work fine in 2466.0.0. Looking online it seems to be related with docker and maybe selinux (https://github.com/cri-o/cri-o/issues/2017 https://github.com/metallb/metallb/issues/21).

I see that the 2492.0.0 updated containerd and the kernel.

**Impact**

I can't run pods with `allowPrivilegeEscalation: false`.

**Environment and steps to reproduce**

1. **Set-up**: Flatcar 2492.0.0 on Packet.
2. **Task**: Running a container.
3. **Action(s)**:

Run docker with `--security-opt=no-new-privileges`:

```
$ grep VERSION_ID /etc/os-release
VERSION_ID=2492.0.0
$ docker run --security-opt=no-new-privileges -it busybox
Unable to find image 'busybox:latest' locally
latest: Pulling from library/busybox
e2334dd9fee4: Pull complete
Digest: sha256:a8cf7ff6367c2afa2a90acd081b484cbded349a7076e7bdf37a05279f276bc12
Status: Downloaded newer image for busybox:latest
standard_init_linux.go:211: exec user process caused "operation not permitted"
```

4. **Error**: [describe the error that was triggered]

```
standard_init_linux.go:211: exec user process caused "operation not permitted"
```

**Expected behavior**

With 2466.0.0 it works fine:
```
$ grep VERSION_ID /etc/os-release
VERSION_ID=2466.0.0
$ docker run --security-opt=no-new-privileges -it busybox
Unable to find image 'busybox:latest' locally
latest: Pulling from library/busybox
e2334dd9fee4: Pull complete
Digest: sha256:a8cf7ff6367c2afa2a90acd081b484cbded349a7076e7bdf37a05279f276bc12
Status: Downloaded newer image for busybox:latest
/ # 
```
  
**Additional information**

It works if you specify `--security-opt label=disable` too. This seems to have happened in the past, see for example: https://github.com/coreos/bugs/issues/1796.

**Comment by dongsupark** [comment] 2020-05-05 16:38
This issue was caused by the recent runc change, https://github.com/flatcar-linux/coreos-overlay/pull/289. Before the PR, runc simply ignored SELinux labels. After the PR, runc does every work around SELinux labels. That's why we start seeing the issue.

On the other hand, Flatcar has a well-known issue about SELinux policy, which does not always work with container runtime. It has been not addressed since 4 years at least. Last year we tried to fix it, though we could not finish it.

So when we debug in Flatcar Alpha 2492.0.0, we see like that:

```
rm /etc/audit/rules.d/80-selinux.rules 
rm /etc/audit/rules.d/99-default.rules 
rm /etc/selinux/mcs 
cp -a /usr/lib/selinux/mcs /etc/selinux 
rm /var/lib/selinux 
cp -a /usr/lib/selinux/policy /var/lib/selinux
semodule -DB 
systemctl restart audit-rules
docker run --security-opt=no-new-privileges -it busybox
```

Then systemd journal says:
```
May 05 16:04:04 localhost audit: SELINUX_ERR op=security_bounded_transition seresult=denied oldcontext=system_u:system_r:kernel_t:s0 newcontext=system_u:system_r:svirt_lxc_net_t:s0:c410,c975
May 05 16:04:04 localhost kernel: audit: type=1401 audit(1588694644.679:69): op=security_bounded_transition seresult=denied oldcontext=system_u:system_r:kernel_t:s0 newcontext=system_u:system_r:svirt_lxc_net_t:s0:c410,c975
```

See also https://github.com/containers/container-selinux/issues/51.

I think it is a good opportunity to do deep-dive into container runtime policy of SELinux.

**Comment by dongsupark** [comment] 2020-05-28 14:13
With Alpha 2513.0.0 or newer, this issue should be fixed.

Though it was fixed just by workarounds. SELinux libs are still not updated.
There is an [open PR](https://github.com/flatcar-linux/coreos-overlay/pull/347) about the SELinux issue.

**Closed as completed by dongsupark** 2020-05-28 14:13 UTC
Labels: kind/bug
