### ISSUE TITLE
polkit.service fail on AWS ARM

### ISSUE THREAD

**Issue by vbatts** [flatcar/Flatcar#214] opened 2020-10-20 11:06 UTC
**Description**

fresh boot of 2661.0.0 and an AWS t4g.medium

**Impact**

System still boots and seems usable enough, but shows as a "degraded" state.
```shell
ip-172-31-64-204 ~ # journalctl -u polkit.service
-- Logs begin at Tue 2020-10-20 11:00:51 UTC, end at Tue 2020-10-20 11:02:33 UTC. --
Oct 20 11:01:25 localhost systemd[1]: Starting Authorization Manager...
Oct 20 11:01:26 localhost polkitd[1342]: Started polkitd version 0.113
Oct 20 11:01:26 ip-172-31-64-204.ec2.internal systemd[1]: polkit.service: Main process exited, code=dumped, status=11/SEGV
Oct 20 11:01:26 ip-172-31-64-204.ec2.internal systemd[1]: polkit.service: Failed with result 'core-dump'.
Oct 20 11:01:26 ip-172-31-64-204.ec2.internal systemd[1]: Failed to start Authorization Manager.
```

**Expected behavior**

normal boot

**Comment by dongsupark** [comment] 2020-10-20 11:27
Duplicate of https://github.com/flatcar-linux/Flatcar/issues/156 ?

**Comment by vbatts** [comment] 2020-10-20 12:14
oh maybe? the other died with 11/SEGV as well, but didn't show a coredump.
And now I find, I forgot to pull the coredump :facepalm:

**Closed as completed** 2020-10-28 12:25 UTC
Labels: kind/bug, channel/alpha
