### ISSUE TITLE
Upgrade Package Request: ignition

### ISSUE THREAD

**Issue by Cougar** [flatcar/Flatcar#326] opened 2021-01-22 14:06 UTC
**Package name and purpose**  
ignition got many enhancements and fixes multiple bugs since 0.34.0 (dated back to Dec 21, 2019). Latest release from CoreOS is v2.9.0

Package upstream:
 - https://github.com/kinvolk/ignition/releases
 - https://github.com/coreos/ignition/releases

**Benefits of upgrading this package** 
One important fix was an ability to use [systemd instantiated services](https://github.com/coreos/ignition/pull/934), merged  to [v2.2.0
](https://github.com/coreos/ignition/releases/tag/v2.2.0)

For example, instead of using
```yaml
systemd:
  units:
    - name: systemd-networkd-wait-online@eno1.service
      enabled: true
    - name: systemd-networkd-wait-online@ens1f1.service
      enabled: true
```
such hack is needed right now:
```yaml
storage:
  files:
  - path: /etc/systemd/system-preset/50-instantiated.preset
    filesystem: root
    contents:
      inline: |
        enable systemd-networkd-wait-online@.service eno1 ens1f1
```

Btw, the `systemd-networkd-wait-online@.service` is a custom unit because `systemd-networkd-wait-online.service` does not wait for all interfaces to become configured - not sure why (`RequiredForOnline=yes` exists in network configuration).

**Additional information**  
When other base components like Linux kernel and Docker get frequent upgrades, ignition has been forgotten for a long time. As time passes the more complicated the upgrade could be. The same goes for systemd #301.

Or are there any other ideas for ignition roadmap by Kinvolk?

**Comment by pothos** [comment] 2021-01-22 14:18
Regarding the wait-online service: The `--any` parameter is enabled by default on Flatcar(/CoreOS) CL: https://github.com/kinvolk/coreos-overlay/blob/main/sys-apps/systemd/files/0004-wait-online-set-any-by-default.patch

**Comment by Cougar** [comment] 2021-01-22 14:29
Ok, this is the problem then. Doesn't look correct solution as it is not possible to disable that any more. Would be better to add `--any` flag to the `/usr/lib/systemd/system/systemd-networkd-wait-online.service` `ExecStart` line..

**Comment by mt-inside** [comment] 2021-03-08 20:18
I have the same question about an Ignition upgrade - is there anything holding it to version 0.x?
The 0.34 version of Ignition (and corresponding 2.x schema) means the ignition terraform provider has to be pinned back one major release.

I'd also point out that when boot fails due to version incompatibility between the supplied Ignition config and the package version, it's pretty hard to find out why - I wouldn't think a beginner would find it. You have to look at the serial console, then there's one line of error, which is pages and pages back due to all the shutdown messages.

Maybe I'm doing it wrong, but this seems to me like the happy path for flatcar - terraform up a Flatcar VM in some cloud, use the terraform provider to render ignition that will configure it. However terraform-provider-ignition hasn't rendered Config Schema 2.x for ages now, so you need to pin to an ancient terraform provider. (which annoyingly is currently broken and hard to work around: https://github.com/community-terraform-providers/terraform-provider-ignition/issues/13#issuecomment-793031854). Surely this is the most basic of use-cases, yet it takes several layers of diagnostics and workaround to get anything done.

**Comment by pothos** [comment] 2021-03-09 11:03
Agree that the newer spec version should be supported but it needs some porting work because we still want the old spec to stay for some time but it was dropped upstream.

**Comment by adamnovak** [comment] 2021-07-12 20:48
Is #387 a duplicate of this? Or does it have slightly different semantics?

**Comment by t-lo** [comment] 2021-07-28 09:27
@adamnovak that's correct, I'll add context from this issue to #387 and close this issue as a dup.

**Comment by t-lo** [comment] 2021-07-28 09:27
Closing in favour of #387 which is more specific.

**Closed as completed by t-lo** 2021-07-28 09:27 UTC
Labels: kind/roadmap, area/packages, component/ignition
