### ISSUE TITLE
Has the GCP image for 2765.2.6 been deleted or the required permissions changed?

### ISSUE THREAD

**Issue by vpnachev** [flatcar/Flatcar#609] opened 2022-01-27 11:37 UTC
Today we have noticed that we no longer can create VMs on GCP using the image id `projects/kinvolk-public/global/images/flatcar-stable-2765-2-6` which was working fine till recently, for example on `2022-01-25T16:12:05.288Z` we have successfully create a VM with this image. 

Now we are facing this error
```
Error 403: Required 'compute.images.useReadOnly' permission for 'projects/kinvolk-public/global/images/flatcar-stable-2765-2-6', forbidden
```

When I try to list the image, I get the same error
```bash
$ gcloud compute images list --project=kinvolk-public --filter="name~'flatcar'"  --uri
ERROR: (gcloud.compute.images.list) Some requests did not succeed:
 - Required 'compute.images.list' permission for 'projects/kinvolk-public'
```

But for reference, I can describe all images `>= 2905.2.0`, e.g.
```bash
$ gcloud compute images describe projects/kinvolk-public/global/images/flatcar-stable-2905-2-0
...
creationTimestamp: '2021-07-28T05:03:28.368-07:00'
deprecated:
  replacement: https://www.googleapis.com/compute/v1/projects/kinvolk-public/global/images/flatcar-stable-2905-2-1
  state: DEPRECATED
description: The Stable channel should be used by production clusters. Versions of
  Flatcar Container Linux are battle-tested within the Beta and Alpha channels before
  being promoted., 2905.2.0, amd64-usr published on 2021-07-28
...
```

It is interesting that this version is also no longer available on https://www.flatcar.org/releases/. 
Overall, this issue is similar to https://github.com/flatcar-linux/Flatcar/issues/456 but for the Google Cloud Platform instead of AWS.

**Comment by pothos** [comment] 2022-01-27 12:22
Thanks for the report, indeed the release entries for

- 2905.2.0
- 2765.2.1
- 2765.2.2
- 2765.2.4
- 2765.2.5
- 2765.2.6
- ok, and more…!

got lost, maybe during the website rework.
Didn't look at GCP.

**Comment by pothos** [comment] 2022-01-27 15:30
Added the lost releases back to the website.

**Comment by sayanchowdhury** [comment] 2023-09-08 11:33
It seems that the issue is resolved. Closing the issue, feel free to re-open if you think otherwise.

**Closed as completed by sayanchowdhury** 2023-09-08 11:33 UTC
Labels: kind/bug, platform/GCP
