### ISSUE TITLE
Terraform can't SSH into stable-3227.2.1

### ISSUE THREAD

**Issue by alpana17** [flatcar/Flatcar#876] opened 2022-10-20 18:37 UTC
Earlier I was using Flatcar 3033.2.4.
Now, my terraform template is not able to login to launched instance. Error is:
Error: timeout - last error: SSH authentication failed (core@18.236.192.11:22): ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain

If I move to Flatcar 3033.2.4, it will start working properly.

**Comment by wayfrro** [comment] 2022-10-21 06:39
Might be worthy to check if it's not due https://github.com/flatcar/Flatcar/issues/847 .

**Comment by jepio** [comment] 2022-10-21 08:16
Hi @alpana17,
What version of terraform are you using? Openssh deprecated older keyexchange mechanisms. You might need to update terraform, this should be the same as this issue: https://github.com/flatcar/Flatcar/issues/757. An alternative you can try is to add the following to your `/etc/ssh/sshd_config` location:
```
HostkeyAlgorithms +ssh-rsa
PubkeyAcceptedAlgorithms +ssh-rsa
```

**Comment by alpana17** [comment] 2022-10-23 18:56
ok
I will try it

**Comment by alpana17** [comment] 2022-10-26 10:28
Currently, we use Terraform v0.12.7
what is the minimum version of terraform that will work??

**Comment by jepio** [comment] 2022-10-26 11:13
Judging by issues on the terraform repository (https://github.com/hashicorp/terraform/issues/30134), v1.2 and newer.

Have you tried adding the two lines to `/etc/ssh/sshd_config` through ignition? If you must use terraform v0.12.7, then that should allow it to keep working.

**Comment by alpana17** [comment] 2022-10-26 18:22
@jepio I tried adding the two lines.
It worked.

**Comment by alpana17** [comment] 2022-10-26 18:24
@jepio But how it worked by adding these two lines?

**Comment by jepio** [comment] 2022-10-27 07:50
Newer openssh disables the ssh-rsa mechanism used in the public key exchange when establishing a connection. Go ssh stack didn't support other key exchange mechanisms until recently. All go binaries that use the ssh stack are affected, all of them need to use the updated go stack to work, or openssh settings need to be changed to re-enable the disabled ssh-rsa mechanism.

**Comment by jepio** [comment] 2022-11-03 07:57
I will close this since the issue is understood.

**Closed as completed by jepio** 2022-11-03 07:57 UTC
