### ISSUE TITLE
extend-filesystems.service fails sometimes

### ISSUE THREAD

**Issue by akunszt** [flatcar/Flatcar#235] opened 2020-11-12 17:32 UTC
Hello!

We're hunting an elusive issue for a long time ago. We noticed that sometimes our Flatcar Linux instances fails to boot up properly. The basic system is up and running but our SystemD services configured through Ignition fails to start at all. They are all masked. It happens very rarely so it's hard to debug but we noticed that when this happens the root filesystem isn't resized properly.

This is a non-working node.
```
ip-10-19-36-22 ~ # df -h /
Filesystem      Size  Used Avail Use% Mounted on
/dev/nvme0n1p9  2.0G   33M  1.9G   2% /
ip-10-19-36-22 ~ # journalctl -u extend-filesystems
-- Logs begin at Thu 2020-11-12 16:23:53 UTC, end at Thu 2020-11-12 16:50:10 UTC. --
Nov 12 16:25:43 localhost systemd[1]: Starting Extend Filesystems...
Nov 12 16:25:43 localhost systemd[1]: extend-filesystems.service: Succeeded.
Nov 12 16:25:43 localhost systemd[1]: Started Extend Filesystems.
```

You can see that the extend-filesystems didn't do anything. This is how it looks like on a working node.

```ip-10-19-100-248 ~ # df -h /
Filesystem      Size  Used Avail Use% Mounted on
/dev/nvme0n1p9  122G  4.0G  113G   4% /
ip-10-19-100-248 ~ # journalctl -u extend-filesystems
-- Logs begin at Thu 2020-11-12 16:21:18 UTC, end at Thu 2020-11-12 17:01:57 UTC. --
Nov 12 16:21:30 localhost systemd[1]: Starting Extend Filesystems...
Nov 12 16:21:30 localhost extend-filesystems[1678]: resize2fs 1.44.5 (15-Dec-2018)
Nov 12 16:21:31 ip-10-19-100-248 extend-filesystems[1678]: Filesystem at /dev/nvme0n1p9 is mounted on /; on-line resizing required
Nov 12 16:21:31 ip-10-19-100-248 extend-filesystems[1678]: old_desc_blocks = 1, new_desc_blocks = 16
Nov 12 16:21:31 ip-10-19-100-248 extend-filesystems[1678]: The filesystem on /dev/nvme0n1p9 is now 32947195 (4k) blocks long.
Nov 12 16:21:31 ip-10-19-100-248 systemd[1]: extend-filesystems.service: Succeeded.
Nov 12 16:21:31 ip-10-19-100-248 systemd[1]: Started Extend Filesystems.
```

Based on the `/usr/lib/flatcar/extend-filesystems` script that line could be the issue.
```
mapfile DEV_LIST < <(lsblk -P -o NAME,PARTTYPE,FSTYPE,MOUNTPOINT)
```

There might be a race condition between this line and filling up the necessary information about the block devices but this is just a wild guess. Maybe it's totally empty, maybe the UUID is missing - the script searches for that UUID later - or the FSTYPE is empty. We couldn't tell.

Our other idea is that the `cgpt resize "${device}"` doesn't do anything as the partition is already at the extended size. On the failed node the `blockdev --getsz /dev/nvme0n1p9` gave back the good, extended value. So when we reran the `extend-filesystems` script it didn't do anything because the old and the new size were the same, but the filesystem was still only 2GiB. Unfortunately on this node we ran the script before we checked the `blockdev`'s output so we can't tell for sure what was the state after the boot finished.

We're using `Flatcar Container Linux by Kinvolk stable (2345.3.0)` on this specific node but we noticed this behaviour for a long time ago even in the old `CoreOS` days. We're running EBS backed EC2 instances in AWS.

Did you see this before? Did anyone else reported this or similar? Does an upgrade will solve this? Can you add a logging line to show what is in the DEV_LIST for future debugging sessions? Also can you add an echo to show the device, old_size and new_size also for future debugging purposes? Is it possible for us to create a PR about this?

Thanks!

**Comment by pothos** [comment] 2020-11-13 01:39
Interaction with block devices and partitions are definitely prone to races. I think if it's hard to reproduce the best is to go through the code that interacts with the devices and think about any obvious race possibilities.

**Comment by akunszt** [comment] 2020-11-16 15:15
I will be on vacation for a week but after that if I create a PR to extend the logging in that script - and maybe add a few extra checks - then is it possible to include that in an upcoming release? Assuming that the code quality is okay. We don't want to deviate from the vanilla/official AMIs if we can but we would like to solve this race condition as it causes hiccups in the scale-up procedure.

**Comment by pothos** [comment] 2020-11-17 03:29
On a first look I think that the `cgpt resize` call directly followed by the block size check is the problem because I had to deal with these issues in UDisks, too. There are three scenarios, the first is that the block device disappeared because the kernel re-reads the partition table, thus getting the size fails and the device is skipped. The second case is that the old size is returned, the third case is the new size. A waiter is needed but unfortunately it's not easy to tell what condition to wait for because either the size stays the same or should change but wasn't updated yet etc.

**Comment by pothos** [comment] 2020-11-17 03:31
Maybe the return code of `cgpt resize` can help, I'll have a look.

**Comment by pothos** [comment] 2020-11-17 03:36
`cgpt` notifies the kernel about the new size, so the second scenario of getting the old size can be left out and it's only needed to retry querying the size.

**Comment by pothos** [comment] 2020-11-17 05:47
I wonder how this is related to the masked services that you configure – why won't it work with the original filesystem size?

**Comment by pothos** [comment] 2020-11-18 03:01
The next Alpha release will have the fix for the race which I think could be a problem. It will also do additional logging so that we can know what is going on:

```
Nov 18 02:57:02 localhost extend-filesystems[878]: Found sr0
Nov 18 02:57:02 localhost extend-filesystems[878]: Found vda
Nov 18 02:57:02 localhost extend-filesystems[878]: Found vda1
Nov 18 02:57:02 localhost extend-filesystems[878]: Found vda2
Nov 18 02:57:02 localhost extend-filesystems[878]: Found vda3
Nov 18 02:57:02 localhost extend-filesystems[878]: Found vda4
Nov 18 02:57:02 localhost extend-filesystems[878]: Found vda6
Nov 18 02:57:02 localhost extend-filesystems[878]: Found vda7
Nov 18 02:57:02 localhost extend-filesystems[878]: Found vda9
Nov 18 02:57:02 localhost extend-filesystems[878]: Checking size of /dev/vda9
Nov 18 02:57:02 localhost systemd[1]: Starting Load cloud-config from /media/configvirtfs...
Nov 18 02:57:02 localhost systemd[1]: motdgen.service: Succeeded.
Nov 18 02:57:02 localhost systemd[1]: Finished Generate /run/flatcar/motd.
Nov 18 02:57:02 localhost systemd[1]: ssh-key-proc-cmdline.service: Succeeded.
Nov 18 02:57:02 localhost systemd[1]: Finished Install an ssh key from /proc/cmdline.
Nov 18 02:57:02 localhost systemd-timesyncd[850]: Initial synchronization to time server 103.38.121.36:123 (0.flatcar.pool.ntp.org).
Nov 18 02:57:03 localhost extend-filesystems[878]: Resized partition /dev/vda9
Nov 18 02:57:03 localhost extend-filesystems[900]: resize2fs 1.45.5 (07-Jan-2020)
Nov 18 02:57:03 localhost kernel: EXT4-fs (vda9): resizing filesystem from 1617920 to 2142715 blocks
Nov 18 02:57:03 localhost systemd-logind[886]: Watching system buttons on /dev/input/event1 (Power Button)
Nov 18 02:57:03 localhost systemd-logind[886]: Watching system buttons on /dev/input/event0 (AT Translated Set 2 keyboard)
Nov 18 02:57:03 localhost systemd-logind[886]: New seat seat0.
Nov 18 02:57:03 localhost systemd[1]: Started User Login Management.
Nov 18 02:57:03 localhost kernel: EXT4-fs (vda9): resized filesystem to 2142715
Nov 18 02:57:03 localhost update_engine[890]: I1118 02:57:03.113535   890 main.cc:89] Flatcar Update Engine starting
Nov 18 02:57:03 localhost systemd[1]: Started Update Engine.
Nov 18 02:57:03 localhost extend-filesystems[900]: Filesystem at /dev/vda9 is mounted on /; on-line resizing required
Nov 18 02:57:03 localhost extend-filesystems[900]: old_desc_blocks = 1, new_desc_blocks = 2
Nov 18 02:57:03 localhost extend-filesystems[900]: The filesystem on /dev/vda9 is now 2142715 (4k) blocks long.
Nov 18 02:57:03 localhost update_engine[890]: I1118 02:57:03.121726   890 update_check_scheduler.cc:74] Next update check in 5m39s
Nov 18 02:57:03 localhost coreos-cloudinit[894]: 2020/11/18 02:57:03 Checking availability of "cloud-drive"
Nov 18 02:57:03 localhost coreos-cloudinit[894]: 2020/11/18 02:57:03 Fetching user-data from datasource of type "cloud-drive"
Nov 18 02:57:03 localhost coreos-cloudinit[894]: 2020/11/18 02:57:03 Attempting to read from "/media/configvirtfs/openstack/latest/user_data"
Nov 18 02:57:03 localhost coreos-cloudinit[894]: 2020/11/18 02:57:03 Fetching meta-data from datasource of type "cloud-drive"
Nov 18 02:57:03 localhost coreos-cloudinit[894]: 2020/11/18 02:57:03 Attempting to read from "/media/configvirtfs/openstack/latest/meta_data.json"
Nov 18 02:57:03 localhost coreos-cloudinit[894]: 2020/11/18 02:57:03 Parsing user-data as cloud-config
Nov 18 02:57:03 localhost coreos-cloudinit[894]: 2020/11/18 02:57:03 Merging cloud-config from meta-data and user-data
Nov 18 02:57:03 localhost systemd[1]: Started Cluster reboot manager.
Nov 18 02:57:03 localhost extend-filesystems[878]: Resized filesystem in /dev/vda9
Nov 18 02:57:03 localhost extend-filesystems[878]: Found usr
Nov 18 02:57:03 localhost systemd[1]: extend-filesystems.service: Succeeded.
```

**Comment by akunszt** [comment] 2020-11-23 11:54
@pothos Thanks for the changes and the fix. I see it's in `2697.0.0` already. We'll deploy it to our test cluster, alas we can deploy only the stable to our production services. So it'll take some time to use - and test - the fix in widespread.

Honestly I didn't instigate why our services were masked when the resize failed. Even if they starts up they can't properly run. The initial size of the filesystem is 2GiB and we usually have 40 to 60GiB of Docker images but not less than 11GiB on every node.

If you agree we can close this now and we can re-open or create a new issue if we hit with this again on a version after `2697.0.0`.

Thank you very much!

**Comment by pothos** [comment] 2020-11-24 04:11
Thanks, yes, testing Alpha would be great. Maybe we can uncover another race. The whole resizing is done after the initramfs – this makes it easy to ensure that the rootfs is there but on the other hand it could mean that downloading large files is possibly not working when the resize takes too long, and a workaround with `After=extend-filesystems.service` would be needed ;)

I'm ok closing now, but please reopen or file a new issue if you find something.

**Closed as completed by pothos** 2020-11-24 04:11 UTC
