### ISSUE TITLE
/etc/sysctl.d/ not loaded on boot

### ISSUE THREAD

**Issue by vbatts** [flatcar/Flatcar#297] opened 2020-12-11 21:12 UTC
**Description**

Setting parameters in `/etc/sysctl.d/*.conf` is not loaded on boot.

**Impact**

settings are not set.

**Environment and steps to reproduce**

1. **Set-up**: discovered on 2605.9.0 in qemu
1. **Action(s)**: 
  a. `mkdir -p /etc/sysctl.d && echo net.ipv4.ip_forward=0 > /etc/sysctl.d/forward.conf`
  b. `systemctl reboot`
  c. `sysctl net.ipv4.ip_forward`

**Expected behavior**

`net.ipv4.ip_forward = 0` but got `net.ipv4.ip_forward = 1`

**Additional info**

`systemctl restart systemd-sysctl` or `sysctl --system` loads the settings just fine.

**Comment by vbatts** [comment] 2020-12-11 21:13
This can be worked around by dropping in a systemd unit to run `sysctl --system` on boot, but this ought to be default behavior.

**Comment by jepio** [comment] 2021-07-20 09:12
Right now `systemd-sysctl` runs in initramfs, and doesn't have access to the sysctl settings that are part of the rootfs. There must be a way to get the unit to rerun/run later.

**Comment by jepio** [comment] 2021-07-20 16:43
The unit actually runs twice so rootfs sysctl get applied, but funnily enough `net.ipv4.ip_forward` is the one setting that is additionally overriden by a systemd patch that we carry https://github.com/kinvolk/coreos-overlay/blob/main/sys-apps/systemd/files/0005-networkd-default-to-kernel-IPForwarding-setting.patch. systemd-networkd applies that setting and happens to run after systemd-sysctl.

So - no bug.

**Comment by ericlake** [comment] 2021-08-12 14:01
We are also seeing issues with getting sysctl changes to persist on reboot. The settings we are trying to change are:
```
net.netfilter.nf_conntrack_tcp_timeout_close_wait=30
net.netfilter.nf_conntrack_tcp_timeout_fin_wait=10
net.netfilter.nf_conntrack_tcp_timeout_time_wait=10
net.netfilter.nf_conntrack_max=3145728
```

The defaults for these settings our our systems is:
```
net.netfilter.nf_conntrack_tcp_timeout_close_wait = 3600
net.netfilter.nf_conntrack_tcp_timeout_fin_wait = 120
net.netfilter.nf_conntrack_tcp_timeout_time_wait = 120
net.netfilter.nf_conntrack_max = 1572864
```

We have followed https://kinvolk.io/docs/flatcar-container-linux/latest/setup/customization/other-settings/#tuning-sysctl-parameters but have observed that only the `fin_wait` and `time_wait` settings persist. If we are quick enough to log in after a reboot we see that the `max` is modified but after a few seconds it is set back to default values.

As @vbatts stated, after a reboot we are able run `sysctl --system` or restart `systemd-sysctl` and have the changes that want applied.

**Comment by jepio** [comment] 2021-08-12 15:18
Hi @ericlake 
I believe what you are seeing is that various services started later on override the settings you statically configured. I confirmed that on a blank install following the instructions all settings persist. But if I then deploy kubernetes on the system I find the following:
```bash
localhost core # grep nf_conntrack -r /var/lib/
/var/lib/docker/containers/0969b38a330ee24af70a113b40873cd0c5d7c23aba47f342f1876587439e165e/0969b38a330ee24af70a113b40873cd0c5d7c23aba47f342f1876587439e165e-json.log:{"log":"I0812 15:12:48.519540       1 conntrack.go:100] Set sysctl 'net/netfilter/nf_conntrack_max' to 1048576\n","stream":"stderr","time":"2021-08-12T15:12:48.519716439Z"}
/var/lib/docker/containers/0969b38a330ee24af70a113b40873cd0c5d7c23aba47f342f1876587439e165e/0969b38a330ee24af70a113b40873cd0c5d7c23aba47f342f1876587439e165e-json.log:{"log":"I0812 15:12:48.519578       1 conntrack.go:52] Setting nf_conntrack_max to 1048576\n","stream":"stderr","time":"2021-08-12T15:12:48.519734918Z"}
/var/lib/docker/containers/0969b38a330ee24af70a113b40873cd0c5d7c23aba47f342f1876587439e165e/0969b38a330ee24af70a113b40873cd0c5d7c23aba47f342f1876587439e165e-json.log:{"log":"I0812 15:12:48.531604       1 conntrack.go:100] Set sysctl 'net/netfilter/nf_conntrack_tcp_timeout_established' to 86400\n","stream":"stderr","time":"2021-08-12T15:12:48.531864442Z"}
/var/lib/docker/containers/0969b38a330ee24af70a113b40873cd0c5d7c23aba47f342f1876587439e165e/0969b38a330ee24af70a113b40873cd0c5d7c23aba47f342f1876587439e165e-json.log:{"log":"I0812 15:12:48.531660       1 conntrack.go:100] Set sysctl 'net/netfilter/nf_conntrack_tcp_timeout_close_wait' to 3600\n","stream":"stderr","time":"2021-08-12T15:12:48.531881058Z"}
localhost core # docker ps -a  | grep 0969
0969b38a330e        bbad1636b30d                      "/usr/local/bin/kube…"   4 minutes ago       Up 4 minutes                                   k8s_kube-proxy_kube-proxy-hpchf_kube-system_cae546f9-3ca2-4029-836a-ae4022be888b_0
```

Would you be able to confirm that this is the same thing happening on your system?

**Comment by ericlake** [comment] 2021-08-12 15:36
Yep. In our case we are using kubespray to deploy kubernetes and it turns out that kube-proxy is rewriting the settings. We are modifying the config map now to bump the settings and testing with another reboot.

```
Aug 12 00:19:00 kube-proxy-6hqfr kube-proxy info I0812 04:19:00.711976       1 conntrack.go:100] Set sysctl 'net/netfilter/nf_conntrack_tcp_timeout_established' to 86400
Aug 12 00:19:00 kube-proxy-6hqfr kube-proxy info I0812 04:19:00.712024       1 conntrack.go:100] Set sysctl 'net/netfilter/nf_conntrack_tcp_timeout_close_wait' to 3600
Aug 12 09:31:11 kube-proxy-mzd62 kube-proxy info I0812 13:31:11.541056       1 conntrack.go:100] Set sysctl 'net/netfilter/nf_conntrack_max' to 1572864
Aug 12 09:31:11 kube-proxy-mzd62 kube-proxy info I0812 13:31:11.552940       1 conntrack.go:100] Set sysctl 'net/netfilter/nf_conntrack_tcp_timeout_established' to 86400
Aug 12 09:31:11 kube-proxy-mzd62 kube-proxy info I0812 13:31:11.552986       1 conntrack.go:100] Set sysctl 'net/netfilter/nf_conntrack_tcp_timeout_close_wait' to 3600
```

**Comment by pothos** [comment] 2021-08-13 13:25
I'll close this now and if wanted we can create new specific tickets, e.g., for disabling `ip_forward` and dropping the systemd patch.

**Closed as completed by pothos** 2021-08-13 13:25 UTC
Labels: kind/bug
