### ISSUE TITLE
Swap file instructions don't work

### ISSUE THREAD

**Issue by pothos** [flatcar/Flatcar#133] opened 2020-06-09 09:07 UTC
**Description**

As reported on IRC, following https://docs.flatcar-linux.org/os/adding-swap/ to add swap file worked a few releases ago but now results in a circular dependency.

**Impact**
Error messages appear in the journal. TODO: Reproduce and see if the swap file is added.

**Environment and steps to reproduce**

1. **Set-up**: TODO: [ describe the environment Flatcar was running in when encountering the bug; Platform etc. ]
2. **Task**: TODO: [ describe the task the OS was performing when encountering the bug ]
3. **Action(s)**: TODO: [ sequence of actions that triggered the bug, see example below ]
  a. TODO: [ requested the start of a new pod or container ]
  b. TODO: [ container image downloaded ]
4. **Error**:
```
sysinit.target: Found ordering cycle on swap.target/start
sysinit.target: Found dependency on var-vm-swapfile.swap/start
sysinit.target: Found dependency on create-swapfile.service/start
sysinit.target: Found dependency on basic.target/start
sysinit.target: Found dependency on paths.target/start
sysinit.target: Found dependency on motdgen.path/start
sysinit.target: Found dependency on sysinit.target/start
sysinit.target: Job swap.target/start deleted to break ordering cycle starting with sysinit.target/start
(sysinit.target depends on swap.target)
```

**Expected behavior**
Swap file should be added without an error message.

A workaround was:
```
[Unit]
Description=Turn on swap
DefaultDependencies=no
Requires=create-swapfile.service
After=create-swapfile.service
Before=umount.target
Conflicts=umount.target
```

**Additional information**
The docs mention that swap files on BTRFS are not recommended, but I recall that this situation has changed and we might want to update the docs in this regard.

**Comment by neilmayhew** [comment] 2020-06-09 15:05
For reference: https://www.freedesktop.org/software/systemd/man/systemd.swap.html#Default%20Dependencies

**Comment by tormath1** [comment] 2022-01-28 10:34
Tried to reproduce the issue with Flatcar-alpha-3127.0.0:

```
mkdir -p /var/vm
fallocate -l 1024m /var/vm/swapfile1
chmod 600 /var/vm/swapfile1
mkswap /var/vm/swapfile1
```

Then:

```
# systemctl cat var-vm-swapfile1.swap
[Unit]
Description=Turn on swap

[Swap]
What=/var/vm/swapfile1

[Install]
WantedBy=multi-user.target
```

Finally:
```
# systemctl enable --now var-vm-swapfile1.swap
Created symlink /etc/systemd/system/multi-user.target.wants/var-vm-swapfile1.swap → /etc/systemd/system/var-vm-swapfile1.swap.
# swapon
NAME              TYPE  SIZE USED PRIO
/var/vm/swapfile1 file 1024M   0B   -2
```

The instructions work as expected, closing the issue. :)

**Closed as completed by tormath1** 2022-01-28 10:34 UTC
Labels: kind/docs

**Comment by neilmayhew** [comment] 2022-01-28 14:42
The problem was in the [Adding swap with a Container Linux Config](https://www.flatcar.org/docs/latest/setup/storage/adding-swap/#adding-swap-with-a-container-linux-config) section of the documentation. I found that I needed to make the following changes to my ignition `config.yml` to get it to work:

```diff
--- a/config.yml	2022-01-28 07:40:28.949963761 -0700
+++ b/config.yml	2021-09-30 17:34:55.957391940 -0600
@@ -77,8 +77,11 @@
       contents: |
         [Unit]
         Description=Turn on swap
+        DefaultDependencies=no
         Requires=create-swapfile.service
         After=create-swapfile.service
+        Before=umount.target
+        Conflicts=umount.target
 
         [Swap]
         What=/var/vm/swapfile
```

**Comment by tormath1** [comment] 2022-01-31 09:04
@neilmayhew thanks for your feedback.

I gave a try with the Container Linux Config that you linked, and it worked without any error on Alpha-3127.0.0, might be related to systemd upgrade:
```
$ free -m
               total        used        free      shared  buff/cache   available
Mem:             973         131         365         254         476         451
Swap:           1023           0        1023
$ systemctl status var-vm-swapfile1.swap
● var-vm-swapfile1.swap - Turn on swap
     Loaded: loaded (8;;file://localhost/etc/systemd/system/var-vm-swapfile1.swap^G/etc/systemd/system/var-vm-swapfile1.swap8;;^G; enabled; vendor preset: en>
     Active: active since Mon 2022-01-31 08:54:43 UTC; 1min 59s ago
       What: /var/vm/swapfile1
      Tasks: 0 (limit: 7410)
     Memory: 60.0K
        CPU: 6ms
     CGroup: /system.slice/var-vm-swapfile1.swap

Jan 31 08:54:43 localhost systemd[1]: Activating swap Turn on swap...
Jan 31 08:54:43 localhost systemd[1]: Activated swap Turn on swap.
```

**Comment by pothos** [comment] 2022-02-03 13:25
I think it makes sense to add `DefaultDependencies=no` to `create-swapfile.service` instead of the `.swap` unit.

**Comment by pothos** [comment] 2022-02-03 14:46
Docs are updated now: https://github.com/flatcar-linux/flatcar-docs/pull/208
