### ISSUE TITLE
There is "metric 1024" for ip command 

### ISSUE THREAD

**Issue by Winnie81** [flatcar/Flatcar#581] opened 2021-12-20 10:17 UTC
## Description

For Flatcar 3033.2.0, result for "ip -br addr show" is as below:
 lo               UNKNOWN        127.0.0.1/8 ::1/128 
ens192      UP             *.*.*.*/20 metric 1024 *::*:*:*:*/64 

For Flatcar 2983.2.0, result for "ip -br addr show" is as below:
lo               UNKNOWN        127.0.0.1/8 ::1/128 
ens192      UP             *.*.*.*/23 *::*:*:*:*/64 

What's for "metric 1024"? It blocks some of our automation testing. Could you please fix it? Thanks.

**Comment by tormath1** [comment] 2021-12-20 11:45
Hi @Winnie81,

`1024` is the default metric value. I'm not sure it's a "bug" and it might be related to the `libmnl` update since `iproute` relies on this lib.

I'll investigate on it though to get the origin of this sudden appearance.

**Comment by Winnie81** [comment] 2021-12-20 11:58
> 

This appearance blocks our testing. Thanks for your investigation.

**Comment by pothos** [comment] 2021-12-20 13:10
I can't reproduce it… Do you also have the problem when using `ip -j addr show`?
Edit: got the output shown and it also is part of the regular output. agree with @tormath1 that it seems to be a new thing to show the metric and not a bug

**Comment by tormath1** [comment] 2021-12-20 16:46
@Winnie81 

I've been through the whole `ip -br addr show` call, I didn't find exactly from where the `metric 1024` comes from but according to the manual page:
```
$ man ip-address
...
       metric NUMBER
              priority of prefix route associated with address.
```

Having the `metric` value is to be expected in the `ip addr` command. As @pothos mentioned, I would recommend to use `ip -j addr show | jq ...` in order to get the _exact_ value you want to continue your test.

**Comment by jepio** [comment] 2022-01-26 15:14
I believe this was added to iproute in 2018 (https://git.kernel.org/pub/scm/network/iproute2/iproute2.git/commit/ip/ipaddress.c?id=78d04c7b27cf42b77ed239e5ce26f2b7f75ee57b), so there's nothing for us to do.

**Comment by pothos** [comment] 2022-01-26 15:40
With these changes being possible in general I think parsing the JSON output `ip -j a` is what we can suggest to avoid breakage. Closing this now.

**Closed as completed by pothos** 2022-01-26 15:40 UTC
Labels: kind/bug
