### ISSUE TITLE
ipset does not work because of incompatible kernel and userspace protocols

### ISSUE THREAD

**Issue by alban** [flatcar/Flatcar#174] opened 2020-08-27 16:14 UTC
**Description**

Flatcar Container Linux by Kinvolk alpha (2605.0.0):
```
$ sudo ipset list
ipset v6.20.1: Kernel support protocol versions 6-7 while userspace supports protocol versions 6-6
Kernel and userspace incompatible: settype by userspace. with revision 1578235808 not supported 
```

**Impact**

I cannot easily inspect ipsets.

**Environment and steps to reproduce**

1. **Set-up**: Lokomotive cluster with calico having configured ipset rules
2. **Task**: list rules fom command line
3. **Action(s)**: `sudo ipset list`
4. **Error**: see above

**Expected behavior**
`ipset list` lists the ipsets, e.g. from Calico

**Additional information**

Workaround:
```
docker run --rm -ti --privileged --net=host ubuntu
apt-get update &>/dev/null && apt-get install -y ipset &>/dev/null && ipset list
```

Related issue: https://bugs.launchpad.net/ubuntu/+source/firewalld/+bug/1821596

Note: this issue does not affect `iptables`: I can use `iptables` without problems.

**Comment by t-lo** [comment] 2020-08-28 09:59
The kernel protocol version warning can be reproduced by feeding a valid command with garbage arguments to `ipset` since the tool will print protocol information if a command failed, no matter `why` the command failed.

Repro without having Calico establish `ipset` rules:
```
$ ipset add garbage bla
ipset v6.20.1: Kernel support protocol versions 6-7 while userspace supports protocol versions 6-6
The set with the given name does not exist
```

**Comment by t-lo** [comment] 2020-08-28 14:07
Updated to `ipset-7.6`, validated that the update fixes the API issue(via flatcar dev container on the Calico host) and merged the fix. Will be included in the upcoming Alpha refresh which we expect to publish early next week.

Closing - please re-open if you continue experiencing issues.

**Closed as completed by t-lo** 2020-08-28 14:07 UTC
Labels: kind/bug
