### ISSUE TITLE
Image-Builder: race between kubeadm and containerd

### ISSUE THREAD

**Issue by t-lo** [flatcar/Flatcar#930] opened 2023-01-04 15:37 UTC
- [ ] Upstream issue: https://github.com/kubernetes-sigs/image-builder/issues/939

**Comment by johananl** [comment] 2023-09-28 12:21
I couldn't reproduce the issue. Implemented a workaround as a precaution in relevant providers. Will close when the upstream issue is closed.

**Comment by johananl** [comment] 2023-10-09 08:23
Upstream work done. Closing.

**Closed as completed by johananl** 2023-10-09 08:23 UTC
Labels: kind/bug, area/cluster-api
