### ISSUE TITLE
403 Error while pulling flatcar SDK

### ISSUE THREAD

**Issue by SuhasreddyN** [flatcar/Flatcar#526] opened 2021-10-05 05:30 UTC
### Discussed in https://github.com/flatcar-linux/Flatcar/discussions/525

<div type='discussions-op-text'>

<sup>Originally posted by **SuhasreddyN** October  5, 2021</sup>
Getting a 403 error when trying to download the SDK:

$ cork create --manifest-branch=flatcar-stable-2765.2.3
2021-10-05T04:51:06Z cork: Detecting SDK version
2021-10-05T04:51:09Z cork: Found SDK version 2905.0.0 from remote repo
2021-10-05T04:51:09Z cork: Downloading SDK version 2905.0.0
2021-10-05T04:51:14Z cork: Download failed: 403 Forbidden: https://storage.googleapis.com/flatcar-jenkins/sdk/amd64/2905.0.0/flatcar-sdk-amd64-2905.0.0.tar.bz2</div>

**Comment by t-lo** [comment] 2021-10-05 07:05
Hi @SuhasreddyN , we're very sorry for the inconvenience. Due to an unexpected (and massive) usage spike in our dev infrastructure we were required to make parts of the infra private for a short time. We are working on resolving this issue and will issue updates to all channels as well as release a new Mantle version later this week.
We track this issue in #523 .

**Comment by sayanchowdhury** [comment] 2021-10-05 10:51
Closing this issue as a duplicate of #523.

**Closed as completed by sayanchowdhury** 2021-10-05 10:51 UTC
